### PR TITLE
Added option for NULL for languages to see all

### LINKED ISSUE #5: List all languages, including codes
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [X]  a suggested code or documentation change, improvement to the code, or feature request

If you set `LanguageCode = NULL` and do not have it in the query, then it can list all voices and the language codes. 

The current `aws.polly`:
``` r
library(aws.polly)
list_voices(language = NULL)
#> Warning in structure(out[["Voices"]], NextToken = out[["NextToken"]]): Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
#>   Consider 'structure(list(), *)' instead.
#> list()
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS Sierra 10.12.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2018-11-14                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package       * version    date       lib source                         
#>  assertthat      0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                 
#>  aws.polly     * 0.1.2      2016-12-08 [1] CRAN (R 3.5.0)                 
#>  aws.signature   0.4.4      2018-07-27 [1] CRAN (R 3.5.0)                 
#>  backports       1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                 
#>  base64enc       0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                 
#>  callr           3.0.0      2018-08-24 [1] CRAN (R 3.5.0)                 
#>  cli             1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                 
#>  crayon          1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                 
#>  curl            3.2        2018-03-28 [1] CRAN (R 3.5.0)                 
#>  debugme         1.1.0      2017-10-22 [1] CRAN (R 3.5.0)                 
#>  desc            1.2.0      2018-10-06 [1] local                          
#>  devtools        2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                 
#>  digest          0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                 
#>  evaluate        0.12       2018-10-09 [1] CRAN (R 3.5.0)                 
#>  fs              1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                 
#>  glue            1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                 
#>  htmltools       0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                 
#>  httr            1.3.1      2017-08-20 [1] CRAN (R 3.5.0)                 
#>  jsonlite        1.5        2017-06-01 [1] CRAN (R 3.5.0)                 
#>  knitr           1.20       2018-09-21 [1] Github (yihui/knitr@0da648b)   
#>  magrittr        1.5        2014-11-22 [1] CRAN (R 3.5.0)                 
#>  MASS            7.3-51     2018-10-16 [1] CRAN (R 3.5.0)                 
#>  memoise         1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                 
#>  pkgbuild        1.0.2      2018-10-16 [1] CRAN (R 3.5.0)                 
#>  pkgload         1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                 
#>  prettyunits     1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                 
#>  processx        3.2.0.9000 2018-11-13 [1] Github (r-lib/processx@8374340)
#>  ps              1.2.1      2018-11-06 [1] CRAN (R 3.5.0)                 
#>  R6              2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                 
#>  Rcpp            0.12.19    2018-10-01 [1] CRAN (R 3.5.1)                 
#>  remotes         2.0.2      2018-10-30 [1] CRAN (R 3.5.0)                 
#>  rlang           0.3.0.1    2018-10-25 [1] CRAN (R 3.5.0)                 
#>  rmarkdown       1.10       2018-06-11 [1] CRAN (R 3.5.0)                 
#>  rprojroot       1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                 
#>  sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                 
#>  signal          0.7-6      2015-07-30 [1] CRAN (R 3.5.0)                 
#>  stringi         1.2.4      2018-07-20 [1] CRAN (R 3.5.0)                 
#>  stringr         1.3.1      2018-05-10 [1] CRAN (R 3.5.0)                 
#>  testthat        2.0.1      2018-10-13 [1] CRAN (R 3.5.0)                 
#>  tuneR           1.3.3      2018-07-08 [1] CRAN (R 3.5.0)                 
#>  usethis         1.4.0.9000 2018-11-13 [1] local                          
#>  withr           2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                 
#>  yaml            2.2.0      2018-07-25 [1] CRAN (R 3.5.0)                 
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

** After Restarting R **

Preposed `aws.polly` PR:

``` r
devtools::install_github("muschellij2/aws.polly")
#> Downloading GitHub repo muschellij2/aws.polly@master
#> 
#>   
   checking for file ‘/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/RtmpS2hX2w/remotesa20042e9593f/muschellij2-aws.polly-ac3de83/DESCRIPTION’ ...
  
✔  checking for file ‘/private/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T/RtmpS2hX2w/remotesa20042e9593f/muschellij2-aws.polly-ac3de83/DESCRIPTION’
#> 
  
─  preparing ‘aws.polly’:
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
─  checking for LF line-endings in source and make files and shell scripts
#> 
  
─  checking for empty or unneeded directories
#> 
  
─  building ‘aws.polly_0.1.5.tar.gz’
#> 
  
   
#> 
library(aws.polly)
list_voices(language = NULL)
#>    AdditionalLanguageCodes Gender        Id LanguageCode
#> 1                     NULL Female     Filiz        tr-TR
#> 2                     NULL Female    Astrid        sv-SE
#> 3                     NULL Female   Tatyana        ru-RU
#> 4                     NULL   Male     Maxim        ru-RU
#> 5                     NULL Female    Carmen        ro-RO
#> 6                     NULL Female      Ines        pt-PT
#> 7                     NULL   Male Cristiano        pt-PT
#> 8                     NULL Female   Vitoria        pt-BR
#> 9                     NULL   Male   Ricardo        pt-BR
#> 10                    NULL Female      Maja        pl-PL
#> 11                    NULL   Male       Jan        pl-PL
#> 12                    NULL   Male     Jacek        pl-PL
#> 13                    NULL Female       Ewa        pl-PL
#> 14                    NULL   Male     Ruben        nl-NL
#> 15                    NULL Female     Lotte        nl-NL
#> 16                    NULL Female       Liv        nb-NO
#> 17                    NULL Female   Seoyeon        ko-KR
#> 18                    NULL   Male    Takumi        ja-JP
#> 19                    NULL Female    Mizuki        ja-JP
#> 20                    NULL   Male   Giorgio        it-IT
#> 21                    NULL Female     Carla        it-IT
#> 22                    NULL Female    Bianca        it-IT
#> 23                    NULL   Male      Karl        is-IS
#> 24                    NULL Female      Dora        is-IS
#> 25                    NULL   Male   Mathieu        fr-FR
#> 26                    NULL Female       Lea        fr-FR
#> 27                    NULL Female    Celine        fr-FR
#> 28                    NULL Female   Chantal        fr-CA
#> 29                    NULL Female  Penelope        es-US
#> 30                    NULL   Male    Miguel        es-US
#> 31                    NULL Female       Mia        es-MX
#> 32                    NULL Female     Lucia        es-ES
#> 33                    NULL   Male   Enrique        es-ES
#> 34                    NULL Female  Conchita        es-ES
#> 35                    NULL   Male   Geraint    en-GB-WLS
#> 36                    NULL Female     Salli        en-US
#> 37                    NULL   Male   Matthew        en-US
#> 38                    NULL Female  Kimberly        en-US
#> 39                    NULL Female    Kendra        en-US
#> 40                    NULL   Male    Justin        en-US
#> 41                    NULL   Male      Joey        en-US
#> 42                    NULL Female    Joanna        en-US
#> 43                    NULL Female       Ivy        en-US
#> 44                    NULL Female   Raveena        en-IN
#> 45                   hi-IN Female     Aditi        en-IN
#> 46                    NULL Female      Emma        en-GB
#> 47                    NULL   Male     Brian        en-GB
#> 48                    NULL Female       Amy        en-GB
#> 49                    NULL   Male   Russell        en-AU
#> 50                    NULL Female    Nicole        en-AU
#> 51                    NULL Female     Vicki        de-DE
#> 52                    NULL Female   Marlene        de-DE
#> 53                    NULL   Male      Hans        de-DE
#> 54                    NULL Female      Naja        da-DK
#> 55                    NULL   Male      Mads        da-DK
#> 56                    NULL Female   Gwyneth        cy-GB
#> 57                    NULL Female     Zhiyu       cmn-CN
#>            LanguageName      Name
#> 1               Turkish     Filiz
#> 2               Swedish    Astrid
#> 3               Russian   Tatyana
#> 4               Russian     Maxim
#> 5              Romanian    Carmen
#> 6            Portuguese      Inês
#> 7            Portuguese Cristiano
#> 8  Brazilian Portuguese   Vitória
#> 9  Brazilian Portuguese   Ricardo
#> 10               Polish      Maja
#> 11               Polish       Jan
#> 12               Polish     Jacek
#> 13               Polish       Ewa
#> 14                Dutch     Ruben
#> 15                Dutch     Lotte
#> 16            Norwegian       Liv
#> 17               Korean   Seoyeon
#> 18             Japanese    Takumi
#> 19             Japanese    Mizuki
#> 20              Italian   Giorgio
#> 21              Italian     Carla
#> 22              Italian    Bianca
#> 23            Icelandic      Karl
#> 24            Icelandic      Dóra
#> 25               French   Mathieu
#> 26               French       Léa
#> 27               French    Céline
#> 28      Canadian French   Chantal
#> 29           US Spanish  Penélope
#> 30           US Spanish    Miguel
#> 31      Mexican Spanish       Mia
#> 32    Castilian Spanish     Lucia
#> 33    Castilian Spanish   Enrique
#> 34    Castilian Spanish  Conchita
#> 35        Welsh English   Geraint
#> 36           US English     Salli
#> 37           US English   Matthew
#> 38           US English  Kimberly
#> 39           US English    Kendra
#> 40           US English    Justin
#> 41           US English      Joey
#> 42           US English    Joanna
#> 43           US English       Ivy
#> 44       Indian English   Raveena
#> 45       Indian English     Aditi
#> 46      British English      Emma
#> 47      British English     Brian
#> 48      British English       Amy
#> 49   Australian English   Russell
#> 50   Australian English    Nicole
#> 51               German     Vicki
#> 52               German   Marlene
#> 53               German      Hans
#> 54               Danish      Naja
#> 55               Danish      Mads
#> 56                Welsh   Gwyneth
#> 57     Chinese Mandarin     Zhiyu
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS Sierra 10.12.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2018-11-14                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package       * version    date       lib
#>  assertthat      0.2.0      2017-04-11 [1]
#>  aws.polly     * 0.1.5      2018-11-14 [1]
#>  aws.signature   0.4.4      2018-07-27 [1]
#>  backports       1.1.2      2017-12-13 [1]
#>  base64enc       0.1-3      2015-07-28 [1]
#>  bit             1.1-14     2018-05-29 [1]
#>  bit64           0.9-7      2017-05-08 [1]
#>  blob            1.1.1      2018-03-25 [1]
#>  callr           3.0.0      2018-08-24 [1]
#>  cli             1.0.1      2018-09-25 [1]
#>  crancache       0.0.0.9000 2017-10-10 [1]
#>  cranlike        1.0.1      2017-08-03 [1]
#>  crayon          1.3.4      2017-09-16 [1]
#>  curl            3.2        2018-03-28 [1]
#>  DBI             1.0.0      2018-05-02 [1]
#>  debugme         1.1.0      2017-10-22 [1]
#>  desc            1.2.0      2018-10-06 [1]
#>  devtools        2.0.1      2018-10-26 [1]
#>  digest          0.6.18     2018-10-10 [1]
#>  evaluate        0.12       2018-10-09 [1]
#>  fs              1.2.6      2018-08-23 [1]
#>  glue            1.3.0      2018-07-17 [1]
#>  htmltools       0.3.6      2017-04-28 [1]
#>  httr            1.3.1      2017-08-20 [1]
#>  jsonlite        1.5        2017-06-01 [1]
#>  knitr           1.20       2018-09-21 [1]
#>  magrittr        1.5        2014-11-22 [1]
#>  MASS            7.3-51     2018-10-16 [1]
#>  memoise         1.1.0      2017-04-21 [1]
#>  parsedate       1.1.3      2017-03-02 [1]
#>  pkgbuild        1.0.2      2018-10-16 [1]
#>  pkgload         1.0.2      2018-10-29 [1]
#>  prettyunits     1.0.2      2015-07-13 [1]
#>  processx        3.2.0.9000 2018-11-13 [1]
#>  ps              1.2.1      2018-11-06 [1]
#>  R6              2.3.0      2018-10-04 [1]
#>  rappdirs        0.3.1      2016-03-28 [1]
#>  Rcpp            0.12.19    2018-10-01 [1]
#>  remotes         2.0.2      2018-10-30 [1]
#>  rlang           0.3.0.1    2018-10-25 [1]
#>  rmarkdown       1.10       2018-06-11 [1]
#>  rprojroot       1.3-2      2018-01-03 [1]
#>  RSQLite         2.1.1      2018-05-06 [1]
#>  sessioninfo     1.1.1      2018-11-05 [1]
#>  signal          0.7-6      2015-07-30 [1]
#>  stringi         1.2.4      2018-07-20 [1]
#>  stringr         1.3.1      2018-05-10 [1]
#>  testthat        2.0.1      2018-10-13 [1]
#>  tuneR           1.3.3      2018-07-08 [1]
#>  usethis         1.4.0.9000 2018-11-13 [1]
#>  withr           2.1.2      2018-03-15 [1]
#>  yaml            2.2.0      2018-07-25 [1]
#>  source                                
#>  CRAN (R 3.5.0)                        
#>  Github (muschellij2/aws.polly@ac3de83)
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  Github (r-lib/crancache@11e6bde)      
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  local                                 
#>  CRAN (R 3.5.1)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  Github (yihui/knitr@0da648b)          
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.1)                        
#>  CRAN (R 3.5.0)                        
#>  Github (r-lib/processx@8374340)       
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.1)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#>  local                                 
#>  CRAN (R 3.5.0)                        
#>  CRAN (R 3.5.0)                        
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by muschellij2**
Please ensure the following before submitting a PR:

 - [X] if suggesting code changes or improvements, [open an issue](https://github.com/cloudyr/aws.polly/issues/new) first
 - [X] for all but trivial changes (e.g., typo fixes), add your name to [DESCRIPTION](https://github.com/cloudyr/aws.polly/blob/master/DESCRIPTION)
 - [X] for all but trivial changes (e.g., typo fixes), documentation your change in [NEWS.md](https://github.com/cloudyr/aws.polly/blob/master/NEWS.md) with a parenthetical reference to the issue number being addressed
 - [X] if changing documentation, edit files in `/R` not `/man` and run `devtools::document()` to update documentation
 - [X] make sure `R CMD check` runs without error before submitting the PR

This fixes #5 for listing all voices.

### CODE REVIEW

**Comment by muschellij2** [comment]
Does this seem to work on your end?

**Comment by muschellij2** [comment]
So I think this works but I'm not sure @cloudyr or @leeper is still maintaining...

**Comment by muschellij2** [comment]
This should now work.  Good to see @antoine-sachet maintaining!

**Comment by antoine-sachet** [comment]
Thanks! Looks good to me, I'll start merging. In the future, please avoid committing your `Rproj` file. It contains your local project options which, if committed, overwrite the project options of other contributors.

Close #5.

**Comment by antoine-sachet** [comment]
Merged manually. Close #5.

Thanks again for your contribution!

**Pull request closed without merging**
